# ========== 雅思词库 50词 ==========
IELTS_WORDS = [
    {"word": "abandon", "phonetic": "/əˈbændən/", "meaning": "放弃；遗弃", "example": "They had to abandon the project."},
    {"word": "abstract", "phonetic": "/ˈæbstrækt/", "meaning": "抽象的；摘要", "example": "The painting was very abstract."},
    {"word": "academic", "phonetic": "/ˌækəˈdemɪk/", "meaning": "学术的；学业的", "example": "Her academic performance improved."},
    {"word": "accommodate", "phonetic": "/əˈkɒmədeɪt/", "meaning": "容纳；适应", "example": "The hotel can accommodate 200 guests."},
    {"word": "accumulate", "phonetic": "/əˈkjuːmjəleɪt/", "meaning": "积累；堆积", "example": "Dust had accumulated on the shelves."},
    {"word": "accurate", "phonetic": "/ˈækjərət/", "meaning": "准确的；精确的", "example": "The report must be accurate."},
    {"word": "acknowledge", "phonetic": "/əkˈnɒlɪdʒ/", "meaning": "承认；致谢", "example": "He acknowledged his mistake."},
    {"word": "acquire", "phonetic": "/əˈkwaɪər/", "meaning": "获得；习得", "example": "She acquired new skills quickly."},
    {"word": "adapt", "phonetic": "/əˈdæpt/", "meaning": "适应；改编", "example": "Animals adapt to their environment."},
    {"word": "adequate", "phonetic": "/ˈædɪkwət/", "meaning": "足够的；适当的", "example": "The food supply was adequate."},
    {"word": "advocate", "phonetic": "/ˈædvəkeɪt/", "meaning": "倡导；拥护者", "example": "She advocates for human rights."},
    {"word": "aggregate", "phonetic": "/ˈæɡrɪɡət/", "meaning": "总计；聚合", "example": "The aggregate score was high."},
    {"word": "allocate", "phonetic": "/ˈæləkeɪt/", "meaning": "分配；分派", "example": "Funds were allocated for research."},
    {"word": "ambiguous", "phonetic": "/æmˈbɪɡjuəs/", "meaning": "模棱两可的；含糊的", "example": "His answer was ambiguous."},
    {"word": "analyze", "phonetic": "/ˈænəlaɪz/", "meaning": "分析；研究", "example": "Scientists analyzed the data carefully."},
    {"word": "anticipate", "phonetic": "/ænˈtɪsɪpeɪt/", "meaning": "预期；预料", "example": "We anticipate good results."},
    {"word": "apparent", "phonetic": "/əˈpærənt/", "meaning": "明显的；表面上的", "example": "The cause was apparent to all."},
    {"word": "assess", "phonetic": "/əˈses/", "meaning": "评估；评价", "example": "Teachers assess students regularly."},
    {"word": "attribute", "phonetic": "/əˈtrɪbjuːt/", "meaning": "归因于；特质", "example": "Success is attributed to hard work."},
    {"word": "bias", "phonetic": "/ˈbaɪəs/", "meaning": "偏见；偏差", "example": "The study showed gender bias."},
    {"word": "capacity", "phonetic": "/kəˈpæsəti/", "meaning": "容量；能力", "example": "The stadium has a large capacity."},
    {"word": "coherent", "phonetic": "/kəʊˈhɪərənt/", "meaning": "连贯的；一致的", "example": "The argument was coherent."},
    {"word": "complex", "phonetic": "/ˈkɒmpleks/", "meaning": "复杂的；综合体", "example": "The issue is very complex."},
    {"word": "concept", "phonetic": "/ˈkɒnsept/", "meaning": "概念；观念", "example": "The concept of democracy is important."},
    {"word": "consequence", "phonetic": "/ˈkɒnsɪkwəns/", "meaning": "结果；后果", "example": "Consider the consequences of your actions."},
    {"word": "context", "phonetic": "/ˈkɒntekst/", "meaning": "背景；上下文", "example": "Understand words in context."},
    {"word": "contribute", "phonetic": "/kənˈtrɪbjuːt/", "meaning": "贡献；捐助", "example": "Everyone contributed to the project."},
    {"word": "crucial", "phonetic": "/ˈkruːʃl/", "meaning": "至关重要的；关键的", "example": "Timing is crucial in this situation."},
    {"word": "demonstrate", "phonetic": "/ˈdemənstreɪt/", "meaning": "证明；示范", "example": "The experiment demonstrates the theory."},
    {"word": "diverse", "phonetic": "/daɪˈvɜːs/", "meaning": "多样的；不同的", "example": "The city has a diverse population."},
    {"word": "dominant", "phonetic": "/ˈdɒmɪnənt/", "meaning": "占主导地位的", "example": "English is the dominant language."},
    {"word": "emerge", "phonetic": "/ɪˈmɜːdʒ/", "meaning": "出现；浮现", "example": "New technologies continue to emerge."},
    {"word": "evaluate", "phonetic": "/ɪˈvæljueɪt/", "meaning": "评价；评估", "example": "Evaluate the pros and cons carefully."},
    {"word": "evidence", "phonetic": "/ˈevɪdəns/", "meaning": "证据；证明", "example": "There is no evidence of this."},
    {"word": "facilitate", "phonetic": "/fəˈsɪlɪteɪt/", "meaning": "促进；使便利", "example": "Technology facilitates communication."},
    {"word": "framework", "phonetic": "/ˈfreɪmwɜːk/", "meaning": "框架；结构", "example": "A legal framework is needed."},
    {"word": "fundamental", "phonetic": "/ˌfʌndəˈmentl/", "meaning": "基本的；根本的", "example": "This is a fundamental right."},
    {"word": "generate", "phonetic": "/ˈdʒenəreɪt/", "meaning": "产生；生成", "example": "Solar panels generate electricity."},
    {"word": "hypothesis", "phonetic": "/haɪˈpɒθəsɪs/", "meaning": "假设；假说", "example": "Test your hypothesis carefully."},
    {"word": "identify", "phonetic": "/aɪˈdentɪfaɪ/", "meaning": "识别；确认", "example": "Identify the main problems first."},
    {"word": "impact", "phonetic": "/ˈɪmpækt/", "meaning": "影响；冲击", "example": "The decision had a huge impact."},
    {"word": "implement", "phonetic": "/ˈɪmplɪment/", "meaning": "实施；执行", "example": "Implement the new policy immediately."},
    {"word": "indicate", "phonetic": "/ˈɪndɪkeɪt/", "meaning": "表明；显示", "example": "Research indicates a clear trend."},
    {"word": "infrastructure", "phonetic": "/ˈɪnfrəstrʌktʃər/", "meaning": "基础设施", "example": "The country needs better infrastructure."},
    {"word": "integrate", "phonetic": "/ˈɪntɪɡreɪt/", "meaning": "整合；融合", "example": "Integrate new students into the class."},
    {"word": "interpret", "phonetic": "/ɪnˈtɜːprɪt/", "meaning": "解释；理解", "example": "Interpret the data carefully."},
    {"word": "investigate", "phonetic": "/ɪnˈvestɪɡeɪt/", "meaning": "调查；研究", "example": "Police investigated the crime scene."},
    {"word": "justify", "phonetic": "/ˈdʒʌstɪfaɪ/", "meaning": "证明正当；辩护", "example": "Can you justify your decision?"},
    {"word": "maintain", "phonetic": "/meɪnˈteɪn/", "meaning": "维持；保持", "example": "Maintain a healthy lifestyle."},
    {"word": "significant", "phonetic": "/sɪɡˈnɪfɪkənt/", "meaning": "重要的；显著的", "example": "There was a significant improvement."},
]

# ========== 四级词库 50词 ==========
CET4_WORDS = [
    {"word": "ability", "phonetic": "/əˈbɪləti/", "meaning": "能力；才能", "example": "She has the ability to learn quickly."},
    {"word": "abroad", "phonetic": "/əˈbrɔːd/", "meaning": "在国外；到国外", "example": "He studied abroad for two years."},
    {"word": "absence", "phonetic": "/ˈæbsəns/", "meaning": "缺席；不在", "example": "His absence was noticed by everyone."},
    {"word": "accept", "phonetic": "/əkˈsept/", "meaning": "接受；承认", "example": "He accepted the job offer gladly."},
    {"word": "account", "phonetic": "/əˈkaʊnt/", "meaning": "账户；说明", "example": "Please open a bank account."},
    {"word": "achieve", "phonetic": "/əˈtʃiːv/", "meaning": "实现；达到", "example": "Hard work helps you achieve goals."},
    {"word": "active", "phonetic": "/ˈæktɪv/", "meaning": "积极的；活跃的", "example": "She is very active in sports."},
    {"word": "actual", "phonetic": "/ˈæktʃuəl/", "meaning": "实际的；真实的", "example": "The actual cost was much higher."},
    {"word": "advance", "phonetic": "/ədˈvɑːns/", "meaning": "前进；进步", "example": "Technology continues to advance."},
    {"word": "affect", "phonetic": "/əˈfekt/", "meaning": "影响；感动", "example": "Weather affects our mood greatly."},
    {"word": "agree", "phonetic": "/əˈɡriː/", "meaning": "同意；赞成", "example": "I agree with your opinion."},
    {"word": "allow", "phonetic": "/əˈlaʊ/", "meaning": "允许；让", "example": "Parents allow children to play outside."},
    {"word": "amount", "phonetic": "/əˈmaʊnt/", "meaning": "数量；总额", "example": "A large amount of money was raised."},
    {"word": "apply", "phonetic": "/əˈplaɪ/", "meaning": "申请；应用", "example": "She applied for a scholarship."},
    {"word": "approach", "phonetic": "/əˈprəʊtʃ/", "meaning": "方法；接近", "example": "Try a different approach."},
    {"word": "argue", "phonetic": "/ˈɑːɡjuː/", "meaning": "争论；主张", "example": "They argued about the decision."},
    {"word": "aspect", "phonetic": "/ˈæspekt/", "meaning": "方面；外貌", "example": "Consider every aspect of the problem."},
    {"word": "assist", "phonetic": "/əˈsɪst/", "meaning": "帮助；协助", "example": "Can you assist me with this task?"},
    {"word": "attach", "phonetic": "/əˈtætʃ/", "meaning": "附上；连接", "example": "Please attach the file to the email."},
    {"word": "attempt", "phonetic": "/əˈtempt/", "meaning": "尝试；企图", "example": "She made an attempt to solve it."},
    {"word": "attitude", "phonetic": "/ˈætɪtjuːd/", "meaning": "态度；看法", "example": "His attitude changed over time."},
    {"word": "available", "phonetic": "/əˈveɪləbl/", "meaning": "可获得的；有空的", "example": "The tickets are still available."},
    {"word": "avoid", "phonetic": "/əˈvɔɪd/", "meaning": "避免；回避", "example": "Try to avoid making mistakes."},
    {"word": "aware", "phonetic": "/əˈweər/", "meaning": "意识到的；知道的", "example": "Be aware of the risks involved."},
    {"word": "balance", "phonetic": "/ˈbæləns/", "meaning": "平衡；余额", "example": "Keep a balance between work and life."},
    {"word": "basic", "phonetic": "/ˈbeɪsɪk/", "meaning": "基本的；基础的", "example": "Learn the basic rules first."},
    {"word": "benefit", "phonetic": "/ˈbenɪfɪt/", "meaning": "好处；受益", "example": "Exercise benefits your health."},
    {"word": "cause", "phonetic": "/kɔːz/", "meaning": "原因；导致", "example": "Pollution causes health problems."},
    {"word": "certain", "phonetic": "/ˈsɜːtn/", "meaning": "确定的；某些", "example": "She is certain about her choice."},
    {"word": "challenge", "phonetic": "/ˈtʃælɪndʒ/", "meaning": "挑战；质疑", "example": "Climate change is a global challenge."},
    {"word": "chance", "phonetic": "/tʃɑːns/", "meaning": "机会；可能性", "example": "Don't miss this chance to succeed."},
    {"word": "change", "phonetic": "/tʃeɪndʒ/", "meaning": "改变；变化", "example": "Change is sometimes necessary."},
    {"word": "choice", "phonetic": "/tʃɔɪs/", "meaning": "选择；抉择", "example": "Make the right choice."},
    {"word": "collect", "phonetic": "/kəˈlekt/", "meaning": "收集；聚集", "example": "He collects stamps as a hobby."},
    {"word": "common", "phonetic": "/ˈkɒmən/", "meaning": "普通的；共同的", "example": "This is a common mistake."},
    {"word": "compare", "phonetic": "/kəmˈpeər/", "meaning": "比较；对比", "example": "Compare the two options carefully."},
    {"word": "complete", "phonetic": "/kəmˈpliːt/", "meaning": "完成；完整的", "example": "Please complete the form."},
    {"word": "consider", "phonetic": "/kənˈsɪdər/", "meaning": "考虑；认为", "example": "Consider all options before deciding."},
    {"word": "continue", "phonetic": "/kənˈtɪnjuː/", "meaning": "继续；持续", "example": "Please continue with your work."},
    {"word": "control", "phonetic": "/kənˈtrəʊl/", "meaning": "控制；管理", "example": "Control your emotions under pressure."},
    {"word": "correct", "phonetic": "/kəˈrekt/", "meaning": "正确的；纠正", "example": "Please correct any mistakes."},
    {"word": "create", "phonetic": "/kriˈeɪt/", "meaning": "创造；创建", "example": "Create a positive learning environment."},
    {"word": "culture", "phonetic": "/ˈkʌltʃər/", "meaning": "文化；培养", "example": "Culture varies across countries."},
    {"word": "decide", "phonetic": "/dɪˈsaɪd/", "meaning": "决定；下决心", "example": "Decide before the deadline."},
    {"word": "describe", "phonetic": "/dɪˈskraɪb/", "meaning": "描述；形容", "example": "Describe what you saw in detail."},
    {"word": "develop", "phonetic": "/dɪˈveləp/", "meaning": "发展；开发", "example": "Develop good study habits early."},
    {"word": "difficult", "phonetic": "/ˈdɪfɪkəlt/", "meaning": "困难的；费力的", "example": "The exam was very difficult."},
    {"word": "discuss", "phonetic": "/dɪˈskʌs/", "meaning": "讨论；商议", "example": "Let's discuss the plan together."},
    {"word": "effect", "phonetic": "/ɪˈfekt/", "meaning": "效果；影响", "example": "The medicine had a positive effect."},
    {"word": "effort", "phonetic": "/ˈefət/", "meaning": "努力；尽力", "example": "Success requires great effort."},
]

# ========== 六级词库 50词 ==========
CET6_WORDS = [
    {"word": "abolish", "phonetic": "/əˈbɒlɪʃ/", "meaning": "废除；废止", "example": "The law was abolished last year."},
    {"word": "absurd", "phonetic": "/əbˈsɜːd/", "meaning": "荒谬的；可笑的", "example": "That idea is completely absurd."},
    {"word": "accelerate", "phonetic": "/əkˈseləreɪt/", "meaning": "加速；促进", "example": "The economy began to accelerate."},
    {"word": "accessible", "phonetic": "/əkˈsesɪbl/", "meaning": "可进入的；易获得的", "example": "Education should be accessible to all."},
    {"word": "accountability", "phonetic": "/əˌkaʊntəˈbɪləti/", "meaning": "责任；问责", "example": "Accountability is key in leadership."},
    {"word": "adamant", "phonetic": "/ˈædəmənt/", "meaning": "坚定的；固执的", "example": "She was adamant about her decision."},
    {"word": "adhere", "phonetic": "/ədˈhɪər/", "meaning": "坚持；遵守", "example": "You must adhere to the rules."},
    {"word": "advent", "phonetic": "/ˈædvent/", "meaning": "出现；到来", "example": "The advent of the internet changed everything."},
    {"word": "adversity", "phonetic": "/ədˈvɜːsəti/", "meaning": "逆境；困难", "example": "She showed great courage in adversity."},
    {"word": "affirm", "phonetic": "/əˈfɜːm/", "meaning": "断言；确认", "example": "He affirmed his commitment to the project."},
    {"word": "affluent", "phonetic": "/ˈæfluənt/", "meaning": "富裕的；丰富的", "example": "They live in an affluent neighborhood."},
    {"word": "aggravate", "phonetic": "/ˈæɡrəveɪt/", "meaning": "加重；激怒", "example": "Stress can aggravate illness."},
    {"word": "alienate", "phonetic": "/ˈeɪliəneɪt/", "meaning": "疏远；使疏离", "example": "His behavior alienated his friends."},
    {"word": "alleviate", "phonetic": "/əˈliːvieɪt/", "meaning": "减轻；缓和", "example": "Medicine can alleviate pain."},
    {"word": "ambivalent", "phonetic": "/æmˈbɪvələnt/", "meaning": "矛盾的；态度不明确的", "example": "She felt ambivalent about leaving."},
    {"word": "anomaly", "phonetic": "/əˈnɒməli/", "meaning": "异常；反常现象", "example": "Scientists detected an anomaly in the data."},
    {"word": "antiquated", "phonetic": "/ˈæntɪkweɪtɪd/", "meaning": "过时的；陈旧的", "example": "The system is completely antiquated."},
    {"word": "apprehensive", "phonetic": "/ˌæprɪˈhensɪv/", "meaning": "忧虑的；担心的", "example": "She was apprehensive about the exam."},
    {"word": "articulate", "phonetic": "/ɑːˈtɪkjələt/", "meaning": "表达清晰的；能言善辩的", "example": "He is very articulate in debates."},
    {"word": "austerity", "phonetic": "/ɒˈsterəti/", "meaning": "紧缩；严峻；朴素", "example": "The government imposed austerity measures."},
    {"word": "benevolent", "phonetic": "/bɪˈnevələnt/", "meaning": "仁慈的；善意的", "example": "She is a benevolent leader."},
    {"word": "bureaucracy", "phonetic": "/bjʊəˈrɒkrəsi/", "meaning": "官僚体制；繁文缛节", "example": "Bureaucracy slows down progress."},
    {"word": "catalyst", "phonetic": "/ˈkætəlɪst/", "meaning": "催化剂；促进因素", "example": "Education is a catalyst for change."},
    {"word": "chronic", "phonetic": "/ˈkrɒnɪk/", "meaning": "慢性的；长期的", "example": "He suffers from chronic pain."},
    {"word": "cognitive", "phonetic": "/ˈkɒɡnɪtɪv/", "meaning": "认知的；认识的", "example": "Cognitive skills improve with practice."},
    {"word": "complacent", "phonetic": "/kəmˈpleɪsnt/", "meaning": "自满的；得意的", "example": "Don't become complacent after success."},
    {"word": "conceive", "phonetic": "/kənˈsiːv/", "meaning": "设想；构思；怀孕", "example": "He conceived a brilliant plan."},
    {"word": "contemplate", "phonetic": "/ˈkɒntəmpleɪt/", "meaning": "沉思；考虑；凝视", "example": "She contemplated her next move."},
    {"word": "contradictory", "phonetic": "/ˌkɒntrəˈdɪktəri/", "meaning": "矛盾的；对立的", "example": "The evidence was contradictory."},
    {"word": "cynical", "phonetic": "/ˈsɪnɪkl/", "meaning": "愤世嫉俗的；冷嘲的", "example": "He has a cynical view of politics."},
    {"word": "deduce", "phonetic": "/dɪˈdjuːs/", "meaning": "推断；演绎", "example": "Deduce the answer from the clues."},
    {"word": "deliberate", "phonetic": "/dɪˈlɪbərət/", "meaning": "深思熟虑的；故意的", "example": "It was a deliberate choice."},
    {"word": "deplete", "phonetic": "/dɪˈpliːt/", "meaning": "耗尽；消耗", "example": "Natural resources are being depleted."},
    {"word": "deteriorate", "phonetic": "/dɪˈtɪəriəreɪt/", "meaning": "恶化；变坏", "example": "Her health began to deteriorate."},
    {"word": "dilemma", "phonetic": "/dɪˈlemə/", "meaning": "困境；两难局面", "example": "She faced a difficult moral dilemma."},
    {"word": "discrepancy", "phonetic": "/dɪˈskrepənsi/", "meaning": "差异；不一致", "example": "There is a discrepancy in the data."},
    {"word": "eloquent", "phonetic": "/ˈeləkwənt/", "meaning": "雄辩的；有说服力的", "example": "She gave an eloquent speech."},
    {"word": "empirical", "phonetic": "/ɪmˈpɪrɪkl/", "meaning": "以经验为依据的；实证的", "example": "Empirical evidence supports the theory."},
    {"word": "endeavor", "phonetic": "/ɪnˈdevər/", "meaning": "努力；尽力；尝试", "example": "She endeavored to finish on time."},
    {"word": "ephemeral", "phonetic": "/ɪˈfemərəl/", "meaning": "短暂的；转瞬即逝的", "example": "Fame can be ephemeral."},
    {"word": "erroneous", "phonetic": "/ɪˈrəʊniəs/", "meaning": "错误的；不正确的", "example": "The report contained erroneous data."},
    {"word": "exacerbate", "phonetic": "/ɪɡˈzæsəbeɪt/", "meaning": "使恶化；加剧", "example": "The drought exacerbated the famine."},
    {"word": "exemplify", "phonetic": "/ɪɡˈzemplɪfaɪ/", "meaning": "举例说明；是…的典型", "example": "This case exemplifies the problem."},
    {"word": "fluctuate", "phonetic": "/ˈflʌktʃueɪt/", "meaning": "波动；起伏", "example": "Prices fluctuate daily in the market."},
    {"word": "formidable", "phonetic": "/ˈfɔːmɪdəbl/", "meaning": "令人敬畏的；强大的", "example": "She is a formidable opponent."},
    {"word": "implicate", "phonetic": "/ˈɪmplɪkeɪt/", "meaning": "牵连；暗示", "example": "He was implicated in the scandal."},
    {"word": "inevitable", "phonetic": "/ɪnˈevɪtəbl/", "meaning": "不可避免的；必然的", "example": "Change is inevitable in life."},
    {"word": "integrity", "phonetic": "/ɪnˈteɡrəti/", "meaning": "诚信；正直；完整性", "example": "Academic integrity must be upheld."},
    {"word": "meticulous", "phonetic": "/məˈtɪkjələs/", "meaning": "一丝不苟的；细心的", "example": "She is meticulous in her work."},
    {"word": "plausible", "phonetic": "/ˈplɔːzɪbl/", "meaning": "似乎合理的；可信的", "example": "That is a plausible explanation."},
]
