# 雅思核心词汇库（600词）
IELTS_WORDS = [
    {"word": "abandon", "phonetic": "/əˈbændən/", "meaning": "放弃；遗弃", "example": "They had to abandon the project."},
    {"word": "abstract", "phonetic": "/ˈæbstrækt/", "meaning": "抽象的；摘要", "example": "The painting was very abstract."},
    {"word": "academic", "phonetic": "/ˌækəˈdemɪk/", "meaning": "学术的；学业的", "example": "Her academic performance improved."},
    {"word": "access", "phonetic": "/ˈækses/", "meaning": "访问；通道；获取", "example": "Students have access to the library."},
    {"word": "accommodate", "phonetic": "/əˈkɒmədeɪt/", "meaning": "容纳；适应；提供住宿", "example": "The hotel can accommodate 200 guests."},
    {"word": "accompany", "phonetic": "/əˈkʌmpəni/", "meaning": "陪伴；伴随", "example": "She accompanied him to the airport."},
    {"word": "accumulate", "phonetic": "/əˈkjuːmjəleɪt/", "meaning": "积累；堆积", "example": "Dust had accumulated on the shelves."},
    {"word": "accurate", "phonetic": "/ˈækjərət/", "meaning": "准确的；精确的", "example": "The report must be accurate."},
    {"word": "achieve", "phonetic": "/əˈtʃiːv/", "meaning": "实现；达到；取得", "example": "She achieved her goals."},
    {"word": "acknowledge", "phonetic": "/əkˈnɒlɪdʒ/", "meaning": "承认；致谢；确认", "example": "He acknowledged his mistake."},
    {"word": "acquire", "phonetic": "/əˈkwaɪər/", "meaning": "获得；习得", "example": "She acquired new skills quickly."},
    {"word": "adapt", "phonetic": "/əˈdæpt/", "meaning": "适应；改编", "example": "Animals adapt to their environment."},
    {"word": "adequate", "phonetic": "/ˈædɪkwət/", "meaning": "足够的；适当的", "example": "The food supply was adequate."},
    {"word": "adjust", "phonetic": "/əˈdʒʌst/", "meaning": "调整；适应", "example": "He adjusted to the new environment."},
    {"word": "administration", "phonetic": "/ədˌmɪnɪˈstreɪʃn/", "meaning": "管理；行政；政府", "example": "The administration made changes."},
    {"word": "advocate", "phonetic": "/ˈædvəkeɪt/", "meaning": "倡导；拥护；律师", "example": "She advocates for human rights."},
    {"word": "affect", "phonetic": "/əˈfekt/", "meaning": "影响；感动", "example": "Pollution affects public health."},
    {"word": "aggregate", "phonetic": "/ˈæɡrɪɡət/", "meaning": "总计；聚合；合计", "example": "The aggregate score was high."},
    {"word": "aid", "phonetic": "/eɪd/", "meaning": "帮助；援助；辅助工具", "example": "Foreign aid was sent to the country."},
    {"word": "allocate", "phonetic": "/ˈæləkeɪt/", "meaning": "分配；分派", "example": "Funds were allocated for research."},
    {"word": "alter", "phonetic": "/ˈɔːltər/", "meaning": "改变；修改", "example": "The plan was altered significantly."},
    {"word": "ambiguous", "phonetic": "/æmˈbɪɡjuəs/", "meaning": "模棱两可的；含糊不清的", "example": "His answer was ambiguous."},
    {"word": "analyze", "phonetic": "/ˈænəlaɪz/", "meaning": "分析；研究", "example": "Scientists analyzed the data."},
    {"word": "annual", "phonetic": "/ˈænjuəl/", "meaning": "每年的；年度的", "example": "The annual report was published."},
    {"word": "anticipate", "phonetic": "/ænˈtɪsɪpeɪt/", "meaning": "预期；预料；期待", "example": "We anticipate good results."},
    {"word": "apparent", "phonetic": "/əˈpærənt/", "meaning": "明显的；表面上的", "example": "The cause was apparent to all."},
    {"word": "apply", "phonetic": "/əˈplaɪ/", "meaning": "申请；应用；适用", "example": "She applied for the position."},
    {"word": "approach", "phonetic": "/əˈprəʊtʃ/", "meaning": "方法；接近；处理", "example": "A new approach is needed."},
    {"word": "appropriate", "phonetic": "/əˈprəʊpriət/", "meaning": "适当的；合适的", "example": "Choose appropriate clothing."},
    {"word": "approximate", "phonetic": "/əˈprɒksɪmət/", "meaning": "近似的；大约的", "example": "The approximate cost is $500."},
    {"word": "arbitrary", "phonetic": "/ˈɑːbɪtrəri/", "meaning": "任意的；武断的", "example": "The decision seemed arbitrary."},
    {"word": "argue", "phonetic": "/ˈɑːɡjuː/", "meaning": "争论；主张；论证", "example": "Economists argue about this issue."},
    {"word": "aspect", "phonetic": "/ˈæspekt/", "meaning": "方面；外观；方位", "example": "Consider every aspect of the plan."},
    {"word": "assess", "phonetic": "/əˈses/", "meaning": "评估；评价", "example": "Teachers assess students regularly."},
    {"word": "assign", "phonetic": "/əˈsaɪn/", "meaning": "分配；指派；布置", "example": "She was assigned a new task."},
    {"word": "assist", "phonetic": "/əˈsɪst/", "meaning": "帮助；协助", "example": "Nurses assist doctors in surgery."},
    {"word": "assume", "phonetic": "/əˈsjuːm/", "meaning": "假设；承担；呈现", "example": "Don't assume anything."},
    {"word": "attitude", "phonetic": "/ˈætɪtjuːd/", "meaning": "态度；看法；姿势", "example": "His attitude changed over time."},
    {"word": "attribute", "phonetic": "/əˈtrɪbjuːt/", "meaning": "归因于；属性；特质", "example": "Success can be attributed to hard work."},
    {"word": "available", "phonetic": "/əˈveɪləbl/", "meaning": "可获得的；有空的", "example": "The tickets are still available."},
    {"word": "aware", "phonetic": "/əˈweər/", "meaning": "意识到的；知道的", "example": "Be aware of the risks."},
    {"word": "barrier", "phonetic": "/ˈbæriər/", "meaning": "障碍；壁垒；屏障", "example": "Language is a major barrier."},
    {"word": "benefit", "phonetic": "/ˈbenɪfɪt/", "meaning": "好处；利益；受益", "example": "Exercise benefits your health."},
    {"word": "bias", "phonetic": "/ˈbaɪəs/", "meaning": "偏见；偏差；使有偏见", "example": "The study showed gender bias."},
    {"word": "capacity", "phonetic": "/kəˈpæsəti/", "meaning": "容量；能力；职位", "example": "The stadium has a large capacity."},
    {"word": "category", "phonetic": "/ˈkætəɡəri/", "meaning": "类别；种类；范畴", "example": "Books are sorted by category."},
    {"word": "cause", "phonetic": "/kɔːz/", "meaning": "原因；事业；导致", "example": "Pollution causes health problems."},
    {"word": "challenge", "phonetic": "/ˈtʃælɪndʒ/", "meaning": "挑战；质疑；要求", "example": "Climate change is a global challenge."},
    {"word": "characteristic", "phonetic": "/ˌkærəktəˈrɪstɪk/", "meaning": "特征；特性；特有的", "example": "Curiosity is a human characteristic."},
    {"word": "circumstance", "phonetic": "/ˈsɜːkəmstæns/", "meaning": "情况；环境；境况", "example": "Under these circumstances, we must act."},
    {"word": "civil", "phonetic": "/ˈsɪvl/", "meaning": "公民的；国内的；有礼貌的", "example": "Civil rights must be protected."},
    {"word": "clarify", "phonetic": "/ˈklærɪfaɪ/", "meaning": "阐明；澄清", "example": "Please clarify your position."},
    {"word": "coherent", "phonetic": "/kəʊˈhɪərənt/", "meaning": "连贯的；一致的", "example": "The argument was coherent."},
    {"word": "collapse", "phonetic": "/kəˈlæps/", "meaning": "崩溃；倒塌；垮掉", "example": "The bridge collapsed in the storm."},
    {"word": "comment", "phonetic": "/ˈkɒment/", "meaning": "评论；注解；发表意见", "example": "She made an insightful comment."},
    {"word": "commit", "phonetic": "/kəˈmɪt/", "meaning": "承诺；犯罪；投入", "example": "He committed to the project."},
    {"word": "complex", "phonetic": "/ˈkɒmpleks/", "meaning": "复杂的；综合体；情结", "example": "The issue is complex."},
    {"word": "component", "phonetic": "/kəmˈpəʊnənt/", "meaning": "组成部分；成分；元件", "example": "Teamwork is a key component of success."},
    {"word": "concept", "phonetic": "/ˈkɒnsept/", "meaning": "概念；观念；想法", "example": "The concept of democracy is important."},
    {"word": "conclude", "phonetic": "/kənˈkluːd/", "meaning": "得出结论；结束；缔结", "example": "The report concluded with recommendations."},
    {"word": "conflict", "phonetic": "/ˈkɒnflɪkt/", "meaning": "冲突；矛盾；争论", "example": "The conflict lasted for years."},
    {"word": "consequence", "phonetic": "/ˈkɒnsɪkwəns/", "meaning": "结果；后果；重要性", "example": "Consider the consequences of your actions."},
    {"word": "consistent", "phonetic": "/kənˈsɪstənt/", "meaning": "一致的；始终如一的", "example": "Be consistent in your approach."},
    {"word": "constitute", "phonetic": "/ˈkɒnstɪtjuːt/", "meaning": "构成；组成；设立", "example": "Women constitute half the workforce."},
    {"word": "construct", "phonetic": "/kənˈstrʌkt/", "meaning": "建造；构建；概念", "example": "They constructed a new bridge."},
    {"word": "context", "phonetic": "/ˈkɒntekst/", "meaning": "背景；上下文；环境", "example": "Understand words in context."},
    {"word": "contract", "phonetic": "/ˈkɒntrækt/", "meaning": "合同；收缩；感染", "example": "Sign the contract before starting."},
    {"word": "contrast", "phonetic": "/ˈkɒntrɑːst/", "meaning": "对比；对照；差异", "example": "There is a stark contrast between them."},
    {"word": "contribute", "phonetic": "/kənˈtrɪbjuːt/", "meaning": "贡献；捐助；投稿", "example": "Everyone contributed to the project."},
    {"word": "controversial", "phonetic": "/ˌkɒntrəˈvɜːʃl/", "meaning": "有争议的；引起争论的", "example": "This is a controversial issue."},
    {"word": "convey", "phonetic": "/kənˈveɪ/", "meaning": "传达；传递；运输", "example": "She conveyed her ideas clearly."},
    {"word": "corporate", "phonetic": "/ˈkɔːpərət/", "meaning": "公司的；团体的", "example": "Corporate responsibility is important."},
    {"word": "correspond", "phonetic": "/ˌkɒrəˈspɒnd/", "meaning": "符合；通信；相当", "example": "The map corresponds to reality."},
    {"word": "criteria", "phonetic": "/kraɪˈtɪəriə/", "meaning": "标准；准则（criterion复数）", "example": "What are the criteria for selection?"},
    {"word": "crucial", "phonetic": "/ˈkruːʃl/", "meaning": "至关重要的；关键的", "example": "Timing is crucial in this situation."},
    {"word": "culture", "phonetic": "/ˈkʌltʃər/", "meaning": "文化；培养；栽培", "example": "Culture varies across countries."},
    {"word": "debate", "phonetic": "/dɪˈbeɪt/", "meaning": "辩论；争论；讨论", "example": "The debate lasted two hours."},
    {"word": "decline", "phonetic": "/dɪˈklaɪn/", "meaning": "下降；衰退；拒绝", "example": "Sales declined last quarter."},
    {"word": "define", "phonetic": "/dɪˈfaɪn/", "meaning": "定义；规定；明确", "example": "Define your goals clearly."},
    {"word": "demonstrate", "phonetic": "/ˈdemənstreɪt/", "meaning": "证明；示范；表示", "example": "The experiment demonstrates the theory."},
    {"word": "derive", "phonetic": "/dɪˈraɪv/", "meaning": "来源；获得；推导", "example": "Many words derive from Latin."},
    {"word": "design", "phonetic": "/dɪˈzaɪn/", "meaning": "设计；计划；图案", "example": "The building's design is innovative."},
    {"word": "despite", "phonetic": "/dɪˈspaɪt/", "meaning": "尽管；不顾", "example": "Despite the rain, they continued."},
    {"word": "determine", "phonetic": "/dɪˈtɜːmɪn/", "meaning": "决定；确定；查明", "example": "Genes determine eye color."},
    {"word": "devote", "phonetic": "/dɪˈvəʊt/", "meaning": "奉献；致力于；专注", "example": "She devoted her life to science."},
    {"word": "differentiate", "phonetic": "/ˌdɪfəˈrenʃieɪt/", "meaning": "区分；使不同；求导", "example": "Can you differentiate between the two?"},
    {"word": "dimension", "phonetic": "/daɪˈmenʃn/", "meaning": "维度；方面；尺寸", "example": "Consider the social dimension."},
    {"word": "diminish", "phonetic": "/dɪˈmɪnɪʃ/", "meaning": "减少；降低；贬低", "example": "His influence gradually diminished."},
    {"word": "distinct", "phonetic": "/dɪˈstɪŋkt/", "meaning": "清晰的；独特的；不同的", "example": "There are two distinct types."},
    {"word": "distribute", "phonetic": "/dɪˈstrɪbjuːt/", "meaning": "分配；分发；分布", "example": "Food was distributed to refugees."},
    {"word": "diverse", "phonetic": "/daɪˈvɜːs/", "meaning": "多样的；不同的", "example": "The city has a diverse population."},
    {"word": "dominant", "phonetic": "/ˈdɒmɪnənt/", "meaning": "占主导地位的；支配的", "example": "English is the dominant language."},
    {"word": "dramatic", "phonetic": "/drəˈmætɪk/", "meaning": "戏剧性的；显著的", "example": "There was a dramatic increase."},
    {"word": "economy", "phonetic": "/ɪˈkɒnəmi/", "meaning": "经济；节约；经济体", "example": "The global economy is changing."},
    {"word": "element", "phonetic": "/ˈelɪmənt/", "meaning": "元素；要素；成分", "example": "Trust is an essential element."},
    {"word": "emerge", "phonetic": "/ɪˈmɜːdʒ/", "meaning": "出现；浮现；兴起", "example": "New technologies continue to emerge."},
    {"word": "emphasize", "phonetic": "/ˈemfəsaɪz/", "meaning": "强调；重视", "example": "She emphasized the importance of safety."},
    {"word": "enable", "phonetic": "/ɪˈneɪbl/", "meaning": "使能够；使可行", "example": "Technology enables global communication."},
    {"word": "encourage", "phonetic": "/ɪnˈkʌrɪdʒ/", "meaning": "鼓励；促进；支持", "example": "Parents encourage children to read."},
    {"word": "environment", "phonetic": "/ɪnˈvaɪrənmənt/", "meaning": "环境；自然环境", "example": "Protect the environment."},
    {"word": "equal", "phonetic": "/ˈiːkwəl/", "meaning": "平等的；相等的；等于", "example": "Everyone deserves equal rights."},
    {"word": "establish", "phonetic": "/ɪˈstæblɪʃ/", "meaning": "建立；设立；确定", "example": "The company was established in 1990."},
    {"word": "evaluate", "phonetic": "/ɪˈvæljueɪt/", "meaning": "评价；评估；求值", "example": "Evaluate the pros and cons."},
    {"word": "evidence", "phonetic": "/ˈevɪdəns/", "meaning": "证据；证明；迹象", "example": "There is no evidence of this."},
    {"word": "evolve", "phonetic": "/ɪˈvɒlv/", "meaning": "进化；发展；演变", "example": "Species evolve over time."},
    {"word": "examine", "phonetic": "/ɪɡˈzæmɪn/", "meaning": "检查；审查；考试", "example": "The doctor examined the patient."},
    {"word": "exclude", "phonetic": "/ɪkˈskluːd/", "meaning": "排除；不包括；拒之门外", "example": "Don't exclude anyone from the group."},
    {"word": "expand", "phonetic": "/ɪkˈspænd/", "meaning": "扩大；扩展；展开", "example": "The company plans to expand."},
    {"word": "explicit", "phonetic": "/ɪkˈsplɪsɪt/", "meaning": "明确的；直接的；清楚的", "example": "Give explicit instructions."},
    {"word": "exploit", "phonetic": "/ɪkˈsplɔɪt/", "meaning": "剥削；利用；开发", "example": "Don't exploit workers."},
    {"word": "expose", "phonetic": "/ɪkˈspəʊz/", "meaning": "暴露；揭露；使接触", "example": "The article exposed corruption."},
    {"word": "facilitate", "phonetic": "/fəˈsɪlɪteɪt/", "meaning": "促进；使便利；帮助", "example": "Technology facilitates communication."},
    {"word": "factor", "phonetic": "/ˈfæktər/", "meaning": "因素；要素；系数", "example": "Diet is a key factor in health."},
    {"word": "feature", "phonetic": "/ˈfiːtʃər/", "meaning": "特征；特点；以…为特色", "example": "The phone has many features."},
    {"word": "flexible", "phonetic": "/ˈfleksɪbl/", "meaning": "灵活的；柔韧的；可变通的", "example": "We need a flexible approach."},
    {"word": "focus", "phonetic": "/ˈfəʊkəs/", "meaning": "焦点；重点；集中于", "example": "Focus on the main issue."},
    {"word": "formulate", "phonetic": "/ˈfɔːmjəleɪt/", "meaning": "制定；系统阐述；配制", "example": "Formulate a clear strategy."},
    {"word": "foundation", "phonetic": "/faʊnˈdeɪʃn/", "meaning": "基础；基金会；创立", "example": "Education is the foundation of success."},
    {"word": "framework", "phonetic": "/ˈfreɪmwɜːk/", "meaning": "框架；结构；体制", "example": "A legal framework is needed."},
    {"word": "function", "phonetic": "/ˈfʌŋkʃn/", "meaning": "功能；作用；运转", "example": "What is the function of this device?"},
    {"word": "fundamental", "phonetic": "/ˌfʌndəˈmentl/", "meaning": "基本的；根本的；基础", "example": "This is a fundamental right."},
    {"word": "generate", "phonetic": "/ˈdʒenəreɪt/", "meaning": "产生；生成；引起", "example": "Solar panels generate electricity."},
    {"word": "global", "phonetic": "/ˈɡləʊbl/", "meaning": "全球的；全面的", "example": "Global temperatures are rising."},
    {"word": "goal", "phonetic": "/ɡəʊl/", "meaning": "目标；目的；球门", "example": "Set achievable goals."},
    {"word": "guarantee", "phonetic": "/ˌɡærənˈtiː/", "meaning": "保证；保障；担保", "example": "There is no guarantee of success."},
    {"word": "guideline", "phonetic": "/ˈɡaɪdlaɪn/", "meaning": "指导方针；准则；指南", "example": "Follow the safety guidelines."},
    {"word": "hypothesis", "phonetic": "/haɪˈpɒθəsɪs/", "meaning": "假设；假说；前提", "example": "Test your hypothesis carefully."},
    {"word": "identify", "phonetic": "/aɪˈdentɪfaɪ/", "meaning": "识别；确认；认同", "example": "Identify the main problems."},
    {"word": "impact", "phonetic": "/ˈɪmpækt/", "meaning": "影响；冲击；碰撞", "example": "The decision had a huge impact."},
    {"word": "implement", "phonetic": "/ˈɪmplɪment/", "meaning": "实施；执行；工具", "example": "Implement the new policy immediately."},
    {"word": "imply", "phonetic": "/ɪmˈplaɪ/", "meaning": "暗示；意味着；隐含", "example": "His silence implied agreement."},
    {"word": "impose", "phonetic": "/ɪmˈpəʊz/", "meaning": "强加；征收；利用", "example": "New taxes were imposed."},
    {"word": "incentive", "phonetic": "/ɪnˈsentɪv/", "meaning": "激励；动机；刺激", "example": "Financial incentives boost productivity."},
    {"word": "incorporate", "phonetic": "/ɪnˈkɔːpəreɪt/", "meaning": "包含；合并；组建公司", "example": "Incorporate feedback into your work."},
    {"word": "indicate", "phonetic": "/ˈɪndɪkeɪt/", "meaning": "表明；指示；显示", "example": "Research indicates a clear trend."},
    {"word": "individual", "phonetic": "/ˌɪndɪˈvɪdʒuəl/", "meaning": "个人；个体；个别的", "example": "Respect individual differences."},
    {"word": "infrastructure", "phonetic": "/ˈɪnfrəstrʌktʃər/", "meaning": "基础设施；基本建设", "example": "The country needs better infrastructure."},
    {"word": "inherent", "phonetic": "/ɪnˈhɪərənt/", "meaning": "固有的；内在的；天生的", "example": "There are inherent risks in the plan."},
    {"word": "initiative", "phonetic": "/ɪˈnɪʃətɪv/", "meaning": "主动权；倡议；创始", "example": "Take the initiative in this project."},
    {"word": "innovative", "phonetic": "/ˈɪnəveɪtɪv/", "meaning": "创新的；革新的", "example": "The company has an innovative approach."},
    {"word": "insight", "phonetic": "/ˈɪnsaɪt/", "meaning": "洞察力；见解；眼力", "example": "She has great insight into human nature."},
    {"word": "integrate", "phonetic": "/ˈɪntɪɡreɪt/", "meaning": "整合；融合；使一体化", "example": "Integrate new students into the class."},
    {"word": "interpret", "phonetic": "/ɪnˈtɜːprɪt/", "meaning": "解释；口译；理解", "example": "Interpret the data carefully."},
    {"word": "investigate", "phonetic": "/ɪnˈvestɪɡeɪt/", "meaning": "调查；研究；侦查", "example": "Police investigated the crime."},
    {"word": "involve", "phonetic": "/ɪnˈvɒlv/", "meaning": "涉及；包括；使参与", "example": "The project involves many stakeholders."},
    {"word": "issue", "phonetic": "/ˈɪʃuː/", "meaning": "问题；议题；发行", "example": "Climate change is a key issue."},
    {"word": "justify", "phonetic": "/ˈdʒʌstɪfaɪ/", "meaning": "证明…正当；为…辩护", "example": "Can you justify your decision?"},
    {"word": "labor", "phonetic": "/ˈleɪbər/", "meaning": "劳动；劳工；工作", "example": "Labor costs are rising."},
    {"word": "largely", "phonetic": "/ˈlɑːdʒli/", "meaning": "大量地；主要地；在很大程度上", "example": "Success is largely due to effort."},
    {"word": "legal", "phonetic": "/ˈliːɡl/", "meaning": "法律的；合法的", "example": "Seek legal advice before signing."},
    {"word": "limitation", "phonetic": "/ˌlɪmɪˈteɪʃn/", "meaning": "局限；限制；缺点", "example": "Every method has its limitations."},
    {"word": "link", "phonetic": "/lɪŋk/", "meaning": "联系；链接；连接", "example": "There is a link between diet and health."},
    {"word": "logic", "phonetic": "/ˈlɒdʒɪk/", "meaning": "逻辑；推理；条理", "example": "The logic of his argument is flawed."},
    {"word": "maintain", "phonetic": "/meɪnˈteɪn/", "meaning": "维持；保持；坚持", "example": "Maintain a healthy lifestyle."},
    {"word": "major", "phonetic": "/ˈmeɪdʒər/", "meaning": "主要的；重大的；专业", "example": "This is a major problem."},
    {"word": "manipulate", "phonetic": "/məˈnɪpjəleɪt/", "meaning": "操纵；操作；控制", "example": "Don't manipulate others."},
    {"word": "mechanism", "phonetic": "/ˈmekənɪzəm/", "meaning": "机制；机械；运作方式", "example": "A feedback mechanism is needed."},
    {"word": "method", "phonetic": "/ˈmeθəd/", "meaning": "方法；方式；秩序", "example": "Use a systematic method."},
    {"word": "migrate", "phonetic": "/maɪˈɡreɪt/", "meaning": "迁移；移居；移植", "example": "Birds migrate in winter."},
    {"word": "minimize", "phonetic": "/ˈmɪnɪmaɪz/", "meaning": "最小化；使降到最低", "example": "Minimize waste wherever possible."},
    {"word": "modify", "phonetic": "/ˈmɒdɪfaɪ/", "meaning": "修改；改变；修饰", "example": "Modify your behavior if needed."},
    {"word": "monitor", "phonetic": "/ˈmɒnɪtər/", "meaning": "监控；显示器；班长", "example": "Monitor the patient's progress."},
    {"word": "motivate", "phonetic": "/ˈməʊtɪveɪt/", "meaning": "激励；激发；促使", "example": "What motivates you to learn?"},
    {"word": "mutual", "phonetic": "/ˈmjuːtʃuəl/", "meaning": "相互的；共同的", "example": "Mutual respect is important."},
    {"word": "negative", "phonetic": "/ˈneɡətɪv/", "meaning": "消极的；负面的；否定的", "example": "Avoid negative thinking."},
    {"word": "network", "phonetic": "/ˈnetwɜːk/", "meaning": "网络；关系网；联播网", "example": "Build a strong professional network."},
    {"word": "norm", "phonetic": "/nɔːm/", "meaning": "标准；规范；常态", "example": "Social norms vary by culture."},
    {"word": "notion", "phonetic": "/ˈnəʊʃn/", "meaning": "概念；观念；想法", "example": "The notion of freedom differs widely."},
    {"word": "obtain", "phonetic": "/əbˈteɪn/", "meaning": "获得；取得；存在", "example": "Obtain permission before entering."},
    {"word": "obvious", "phonetic": "/ˈɒbviəs/", "meaning": "明显的；显而易见的", "example": "The answer is obvious."},
    {"word": "occupy", "phonetic": "/ˈɒkjəpaɪ/", "meaning": "占据；占领；使忙碌", "example": "The army occupied the city."},
    {"word": "occur", "phonetic": "/əˈkɜːr/", "meaning": "发生；出现；想到", "example": "Accidents can occur at any time."},
    {"word": "oppose", "phonetic": "/əˈpəʊz/", "meaning": "反对；阻止；使对立", "example": "Many people oppose the new law."},
    {"word": "option", "phonetic": "/ˈɒpʃn/", "meaning": "选择；选项；期权", "example": "Consider all available options."},
    {"word": "outcome", "phonetic": "/ˈaʊtkʌm/", "meaning": "结果；结局；后果", "example": "The outcome was unexpected."},
    {"word": "overall", "phonetic": "/ˌəʊvərˈɔːl/", "meaning": "总体的；全面的；总体上", "example": "The overall performance was good."},
    {"word": "overlap", "phonetic": "/ˌəʊvəˈlæp/", "meaning": "重叠；交叠；部分相同", "example": "The two fields overlap considerably."},
    {"word": "participate", "phonetic": "/pɑːˈtɪsɪpeɪt/", "meaning": "参与；参加", "example": "Everyone should participate."},
    {"word": "perceive", "phonetic": "/pəˈsiːv/", "meaning": "感知；察觉；认为", "example": "How do you perceive this issue?"},
    {"word": "perspective", "phonetic": "/pəˈspektɪv/", "meaning": "观点；视角；透视", "example": "Look at it from a different perspective."},
    {"word": "phenomenon", "phonetic": "/fɪˈnɒmɪnən/", "meaning": "现象；奇迹；非凡的人", "example": "Climate change is a global phenomenon."},
    {"word": "policy", "phonetic": "/ˈpɒləsi/", "meaning": "政策；方针；保险单", "example": "The government changed its policy."},
    {"word": "positive", "phonetic": "/ˈpɒzətɪv/", "meaning": "积极的；正面的；确定的", "example": "Maintain a positive attitude."},
    {"word": "potential", "phonetic": "/pəˈtenʃl/", "meaning": "潜力；可能性；潜在的", "example": "She has great potential."},
    {"word": "poverty", "phonetic": "/ˈpɒvəti/", "meaning": "贫穷；贫困；匮乏", "example": "Many families live in poverty."},
    {"word": "predict", "phonetic": "/prɪˈdɪkt/", "meaning": "预测；预言；预报", "example": "Scientists predict rising sea levels."},
    {"word": "predominant", "phonetic": "/prɪˈdɒmɪnənt/", "meaning": "主要的；占主导地位的", "example": "English is the predominant language."},
    {"word": "preserve", "phonetic": "/prɪˈzɜːv/", "meaning": "保存；保护；保持", "example": "Preserve natural habitats."},
    {"word": "primary", "phonetic": "/ˈpraɪməri/", "meaning": "主要的；初级的；基本的", "example": "Education is a primary concern."},
    {"word": "principle", "phonetic": "/ˈprɪnsɪpl/", "meaning": "原则；原理；主义", "example": "Act according to your principles."},
    {"word": "priority", "phonetic": "/praɪˈɒrəti/", "meaning": "优先；优先权；重要事项", "example": "Health should be a top priority."},
    {"word": "process", "phonetic": "/ˈprəʊses/", "meaning": "过程；处理；加工", "example": "Learning is a gradual process."},
    {"word": "promote", "phonetic": "/prəˈməʊt/", "meaning": "促进；宣传；晋升", "example": "Exercise promotes good health."},
    {"word": "proportion", "phonetic": "/prəˈpɔːʃn/", "meaning": "比例；部分；均衡", "example": "A large proportion of students passed."},
    {"word": "propose", "phonetic": "/prəˈpəʊz/", "meaning": "提议；建议；求婚", "example": "She proposed a new solution."},
    {"word": "provide", "phonetic": "/prəˈvaɪd/", "meaning": "提供；供给；规定", "example": "The government provides healthcare."},
    {"word": "pursue", "phonetic": "/pəˈsjuː/", "meaning": "追求；从事；继续", "example": "Pursue your dreams with passion."},
    {"word": "rational", "phonetic": "/ˈræʃnəl/", "meaning": "理性的；合理的；有理由的", "example": "Make rational decisions."},
    {"word": "react", "phonetic": "/riˈækt/", "meaning": "反应；起反应；反对", "example": "How did she react to the news?"},
    {"word": "reduce", "phonetic": "/rɪˈdjuːs/", "meaning": "减少；降低；简化", "example": "Reduce carbon emissions now."},
    {"word": "refer", "phonetic": "/rɪˈfɜːr/", "meaning": "提到；参考；转介", "example": "Refer to the dictionary for help."},
    {"word": "reform", "phonetic": "/rɪˈfɔːm/", "meaning": "改革；改良；改正", "example": "Education reform is needed."},
    {"word": "regulate", "phonetic": "/ˈreɡjəleɪt/", "meaning": "管理；调节；规范", "example": "The government regulates the industry."},
    {"word": "reinforce", "phonetic": "/ˌriːɪnˈfɔːs/", "meaning": "加强；强化；增援", "example": "Reinforce your argument with evidence."},
    {"word": "reject", "phonetic": "/rɪˈdʒekt/", "meaning": "拒绝；排斥；否定", "example": "The proposal was rejected."},
    {"word": "relevant", "phonetic": "/ˈreləvənt/", "meaning": "相关的；有意义的", "example": "Provide relevant examples."},
    {"word": "rely", "phonetic": "/rɪˈlaɪ/", "meaning": "依靠；依赖；信任", "example": "Don't rely on luck."},
    {"word": "require", "phonetic": "/rɪˈkwaɪər/", "meaning": "需要；要求；规定", "example": "The job requires experience."},
    {"word": "research", "phonetic": "/rɪˈsɜːtʃ/", "meaning": "研究；调查；探究", "example": "Research shows many benefits."},
    {"word": "resolve", "phonetic": "/rɪˈzɒlv/", "meaning": "解决；决心；分解", "example": "Resolve conflicts peacefully."},
    {"word": "resource", "phonetic": "/rɪˈzɔːs/", "meaning": "资源；财力；谋略", "example": "Natural resources are limited."},
    {"word": "respond", "phonetic": "/rɪˈspɒnd/", "meaning": "回应；作出反应", "example": "Respond to emails promptly."},
    {"word": "restrict", "phonetic": "/rɪˈstrɪkt/", "meaning": "限制；约束；控制", "example": "Access to the area was restricted."},
    {"word": "reveal", "phonetic": "/rɪˈviːl/", "meaning": "揭示；透露；展示", "example": "The report revealed serious flaws."},
    {"word": "role", "phonetic": "/rəʊl/", "meaning": "角色；职能；作用", "example": "Education plays a key role."},
    {"word": "scale", "phonetic": "/skeɪl/", "meaning": "规模；比例；刻度", "example": "The project was large in scale."},
    {"word": "sector", "phonetic": "/ˈsektər/", "meaning": "部门；行业；扇形", "example": "The public sector employs many people."},
    {"word": "seek", "phonetic": "/siːk/", "meaning": "寻找；寻求；试图", "example": "Seek professional advice."},
    {"word": "select", "phonetic": "/sɪˈlekt/", "meaning": "选择；挑选；精选的", "example": "Select the best candidate."},
    {"word": "significant", "phonetic": "/sɪɡˈnɪfɪkənt/", "meaning": "重要的；显著的；意义重大", "example": "There was a significant improvement."},
    {"word": "simulate", "phonetic": "/ˈsɪmjəleɪt/", "meaning": "模拟；仿真；假装", "example": "The software simulates real situations."},
    {"word": "situation", "phonetic": "/ˌsɪtʃuˈeɪʃn/", "meaning": "情况；处境；位置", "example": "The situation is improving."},
    {"word": "solution", "phonetic": "/səˈluːʃn/", "meaning": "解决方案；溶液；解答", "example": "Find a practical solution."},
    {"word": "source", "phonetic": "/sɔːs/", "meaning": "来源；根源；信息源", "example": "Cite your sources correctly."},
    {"word": "specific", "phonetic": "/spəˈsɪfɪk/", "meaning": "具体的；特定的；明确的", "example": "Be specific in your request."},
    {"word": "stable", "phonetic": "/ˈsteɪbl/", "meaning": "稳定的；牢固的；马厩", "example": "Prices have remained stable."},
    {"word": "strategy", "phonetic": "/ˈstrætədʒi/", "meaning": "战略；策略；计划", "example": "Develop a clear strategy."},
    {"word": "structure", "phonetic": "/ˈstrʌktʃər/", "meaning": "结构；构造；组织", "example": "The structure of the essay is clear."},
    {"word": "submit", "phonetic": "/səbˈmɪt/", "meaning": "提交；服从；忍受", "example": "Submit your application by Friday."},
    {"word": "sufficient", "phonetic": "/səˈfɪʃnt/", "meaning": "足够的；充分的", "example": "There is sufficient evidence."},
    {"word": "suggest", "phonetic": "/səˈdʒest/", "meaning": "建议；暗示；表明", "example": "Research suggests a link."},
    {"word": "summarize", "phonetic": "/ˈsʌməraɪz/", "meaning": "总结；概括；摘要", "example": "Summarize the main points."},
    {"word": "support", "phonetic": "/səˈpɔːt/", "meaning": "支持；支撑；资助", "example": "Support your claims with data."},
    {"word": "sustain", "phonetic": "/səˈsteɪn/", "meaning": "维持；支撑；遭受", "example": "Sustain economic growth."},
    {"word": "target", "phonetic": "/ˈtɑːɡɪt/", "meaning": "目标；靶子；针对", "example": "Set realistic targets."},
    {"word": "technique", "phonetic": "/tekˈniːk/", "meaning": "技术；方法；技巧", "example": "Use a new technique."},
    {"word": "technology", "phonetic": "/tekˈnɒlədʒi/", "meaning": "技术；工艺；科技", "example": "Technology changes rapidly."},
    {"word": "theory", "phonetic": "/ˈθɪəri/", "meaning": "理论；学说；推测", "example": "Darwin's theory of evolution."},
    {"word": "transform", "phonetic": "/trænsˈfɔːm/", "meaning": "转变；改造；变换", "example": "Technology transformed society."},
    {"word": "trend", "phonetic": "/trend/", "meaning": "趋势；潮流；走向", "example": "Follow the latest trends."},
    {"word": "undermine", "phonetic": "/ˌʌndəˈmaɪn/", "meaning": "削弱；破坏；挖掘", "example": "Don't undermine your colleagues."},
    {"word": "unique", "phonetic": "/juˈniːk/", "meaning": "独特的；唯一的；无与伦比的", "example": "Everyone is unique."},
    {"word": "utilize", "phonetic": "/ˈjuːtɪlaɪz/", "meaning": "利用；使用；运用", "example": "Utilize available resources."},
    {"word": "valid", "phonetic": "/ˈvælɪd/", "meaning": "有效的；合理的；正当的", "example": "Your argument is valid."},
    {"word": "variable", "phonetic": "/ˈveəriəbl/", "meaning": "变量；可变的；易变的", "example": "Many variables affect the outcome."},
    {"word": "vary", "phonetic": "/ˈveəri/", "meaning": "变化；不同；使多样化", "example": "Results vary from person to person."},
    {"word": "visible", "phonetic": "/ˈvɪzɪbl/", "meaning": "可见的；明显的；显著的", "example": "Progress is now visible."},
    {"word": "widespread", "phonetic": "/ˈwaɪdspred/", "meaning": "普遍的；广泛的；遍布的", "example": "Poverty is widespread in the region."},
    {"word": "yield", "phonetic": "/jiːld/", "meaning": "产生；屈服；产量", "example": "Hard work yields good results."},
    {"word": "abolish", "phonetic": "/əˈbɒlɪʃ/", "meaning": "废除；废止", "example": "Slavery was abolished in the 19th century."},
    {"word": "absorb", "phonetic": "/əbˈzɔːb/", "meaning": "吸收；理解；承受", "example": "Plants absorb sunlight."},
    {"word": "abstract", "phonetic": "/ˈæbstrækt/", "meaning": "抽象的；摘要；提取", "example": "Write an abstract for your paper."},
    {"word": "accelerate", "phonetic": "/əkˈseləreɪt/", "meaning": "加速；促进", "example": "The car accelerated quickly."},
    {"word": "accomplish", "phonetic": "/əˈkʌmplɪʃ/", "meaning": "完成；实现；达到", "example": "Accomplish your daily goals."},
    {"word": "accountable", "phonetic": "/əˈkaʊntəbl/", "meaning": "负有责任的；应受谴责的", "example": "Leaders must be accountable."},
    {"word": "accurate", "phonetic": "/ˈækjərət/", "meaning": "准确的；精确的", "example": "Accurate data is essential."},
    {"word": "adhere", "phonetic": "/ədˈhɪər/", "meaning": "坚持；遵守；粘附", "example": "Adhere to the rules."},
    {"word": "adjacent", "phonetic": "/əˈdʒeɪsnt/", "meaning": "邻近的；毗邻的", "example": "The park is adjacent to the school."},
    {"word": "administration", "phonetic": "/ədˌmɪnɪˈstreɪʃn/", "meaning": "行政；管理；政府", "example": "University administration handles policies."},
    {"word": "adversity", "phonetic": "/ədˈvɜːsəti/", "meaning": "逆境；困境；不幸", "example": "She overcame great adversity."},
    {"word": "affluent", "phonetic": "/ˈæfluənt/", "meaning": "富裕的；富有的", "example": "An affluent neighborhood."},
    {"word": "agenda", "phonetic": "/əˈdʒendə/", "meaning": "议程；日程；目标", "example": "What's on today's agenda?"},
    {"word": "alleviate", "phonetic": "/əˈliːvieɪt/", "meaning": "减轻；缓解；缓和", "example": "Medicine can alleviate pain."},
    {"word": "alternative", "phonetic": "/ɔːlˈtɜːnətɪv/", "meaning": "替代的；另一选择", "example": "Find an alternative solution."},
    {"word": "ambition", "phonetic": "/æmˈbɪʃn/", "meaning": "野心；抱负；渴望", "example": "His ambition drove him to succeed."},
    {"word": "analogy", "phonetic": "/əˈnælədʒi/", "meaning": "类比；比拟；相似处", "example": "Draw an analogy between two things."},
    {"word": "anonymous", "phonetic": "/əˈnɒnɪməs/", "meaning": "匿名的；无名的", "example": "The donor wished to remain anonymous."},
    {"word": "anxiety", "phonetic": "/æŋˈzaɪəti/", "meaning": "焦虑；忧虑；渴望", "example": "Exam anxiety is common."},
    {"word": "appeal", "phonetic": "/əˈpiːl/", "meaning": "吸引力；呼吁；上诉", "example": "The campaign appealed to voters."},
    {"word": "application", "phonetic": "/ˌæplɪˈkeɪʃn/", "meaning": "申请；应用；涂抹", "example": "Submit your application online."},
    {"word": "appoint", "phonetic": "/əˈpɔɪnt/", "meaning": "任命；指定；约定", "example": "She was appointed director."},
    {"word": "argue", "phonetic": "/ˈɑːɡjuː/", "meaning": "论证；争辩；主张", "example": "He argued his point persuasively."},
    {"word": "arise", "phonetic": "/əˈraɪz/", "meaning": "产生；出现；起身", "example": "Problems may arise unexpectedly."},
    {"word": "artificial", "phonetic": "/ˌɑːtɪˈfɪʃl/", "meaning": "人工的；人造的；虚假的", "example": "Artificial intelligence is advancing."},
    {"word": "assert", "phonetic": "/əˈsɜːt/", "meaning": "断言；维护；坚持", "example": "He asserted his innocence."},
    {"word": "assumption", "phonetic": "/əˈsʌmpʃn/", "meaning": "假定；设想；承担", "example": "Don't make assumptions."},
    {"word": "attain", "phonetic": "/əˈteɪn/", "meaning": "达到；获得；实现", "example": "Attain your full potential."},
    {"word": "authoritative", "phonetic": "/ɔːˈθɒrɪtətɪv/", "meaning": "权威的；可靠的", "example": "Use authoritative sources."},
    {"word": "autonomy", "phonetic": "/ɔːˈtɒnəmi/", "meaning": "自主；自治；自主权", "example": "Students need autonomy to learn."},
    {"word": "benchmark", "phonetic": "/ˈbentʃmɑːk/", "meaning": "基准；标准；参照点", "example": "Set a benchmark for performance."},
    {"word": "biological", "phonetic": "/ˌbaɪəˈlɒdʒɪkl/", "meaning": "生物的；生物学的", "example": "Biological research is advancing."},
    {"word": "boycott", "phonetic": "/ˈbɔɪkɒt/", "meaning": "抵制；联合抵制", "example": "Consumers boycotted the product."},
    {"word": "bureaucracy", "phonetic": "/bjʊəˈrɒkrəsi/", "meaning": "官僚体制；繁文缛节", "example": "Bureaucracy slows progress."},
    {"word": "catalyst", "phonetic": "/ˈkætəlɪst/", "meaning": "催化剂；促进因素", "example": "Education is a catalyst for change."},
    {"word": "cease", "phonetic": "/siːs/", "meaning": "停止；终止", "example": "Hostilities must cease immediately."},
    {"word": "chronic", "phonetic": "/ˈkrɒnɪk/", "meaning": "慢性的；长期的；积习难改的", "example": "He suffers from chronic pain."},
    {"word": "cite", "phonetic": "/saɪt/", "meaning": "引用；举例；传唤", "example": "Cite your sources properly."},
    {"word": "collaborate", "phonetic": "/kəˈlæbəreɪt/", "meaning": "合作；协作", "example": "Scientists collaborate across borders."},
    {"word": "commodity", "phonetic": "/kəˈmɒdəti/", "meaning": "商品；货物；有用的东西", "example": "Oil is a valuable commodity."},
    {"word": "compensation", "phonetic": "/ˌkɒmpenˈseɪʃn/", "meaning": "补偿；赔偿；薪酬", "example": "Compensation was paid to victims."},
    {"word": "competent", "phonetic": "/ˈkɒmpɪtənt/", "meaning": "有能力的；胜任的", "example": "She is a competent manager."},
    {"word": "compile", "phonetic": "/kəmˈpaɪl/", "meaning": "汇编；编辑；收集", "example": "Compile a list of references."},
    {"word": "comply", "phonetic": "/kəmˈplaɪ/", "meaning": "遵守；服从；顺从", "example": "Comply with safety regulations."},
    {"word": "comprehend", "phonetic": "/ˌkɒmprɪˈhend/", "meaning": "理解；领悟；包含", "example": "I cannot comprehend his motives."},
    {"word": "concede", "phonetic": "/kənˈsiːd/", "meaning": "承认；退让；让步", "example": "He conceded that he was wrong."},
    {"word": "confront", "phonetic": "/kənˈfrʌnt/", "meaning": "面对；对抗；使对质", "example": "Confront your fears."},
    {"word": "consecutive", "phonetic": "/kənˈsekjətɪv/", "meaning": "连续的；连贯的", "example": "It rained for five consecutive days."},
    {"word": "consent", "phonetic": "/kənˈsent/", "meaning": "同意；准许；赞成", "example": "Always obtain informed consent."},
    {"word": "consolidate", "phonetic": "/kənˈsɒlɪdeɪt/", "meaning": "巩固；合并；整合", "example": "Consolidate your learning."},
    {"word": "contemporary", "phonetic": "/kənˈtemprəri/", "meaning": "当代的；同时代的", "example": "Contemporary art is diverse."},
    {"word": "contrary", "phonetic": "/ˈkɒntrəri/", "meaning": "相反的；对立的；相反", "example": "On the contrary, I agree."},
    {"word": "cope", "phonetic": "/kəʊp/", "meaning": "应对；处理；克服", "example": "She coped well under pressure."},
    {"word": "corruption", "phonetic": "/kəˈrʌpʃn/", "meaning": "腐败；贿赂；堕落", "example": "Corruption undermines democracy."},
    {"word": "credible", "phonetic": "/ˈkredɪbl/", "meaning": "可信的；可靠的", "example": "She is a credible witness."},
    {"word": "currency", "phonetic": "/ˈkʌrənsi/", "meaning": "货币；流通；通用", "example": "The currency was devalued."},
    {"word": "curriculum", "phonetic": "/kəˈrɪkjələm/", "meaning": "课程；课程体系", "example": "The curriculum needs updating."},
    {"word": "decisive", "phonetic": "/dɪˈsaɪsɪv/", "meaning": "决定性的；果断的", "example": "Take decisive action now."},
    {"word": "deduce", "phonetic": "/dɪˈdjuːs/", "meaning": "推断；推论；演绎", "example": "Deduce the answer from the clues."},
    {"word": "delegate", "phonetic": "/ˈdelɪɡeɪt/", "meaning": "委托；代表；代表团成员", "example": "Delegate tasks effectively."},
    {"word": "democratic", "phonetic": "/ˌdeməˈkrætɪk/", "meaning": "民主的；民主主义的", "example": "A democratic society values freedom."},
    {"word": "deplete", "phonetic": "/dɪˈpliːt/", "meaning": "耗尽；消耗；使减少", "example": "Resources are being depleted."},
    {"word": "depression", "phonetic": "/dɪˈpreʃn/", "meaning": "抑郁症；萧条；压低", "example": "Economic depression affects many."},
    {"word": "derive", "phonetic": "/dɪˈraɪv/", "meaning": "获得；起源；推导", "example": "Derive meaning from your work."},
    {"word": "desirable", "phonetic": "/dɪˈzaɪərəbl/", "meaning": "值得向往的；令人满意的", "example": "Experience is desirable for this role."},
    {"word": "detect", "phonetic": "/dɪˈtekt/", "meaning": "发现；探测；查明", "example": "Detect errors early."},
    {"word": "deviate", "phonetic": "/ˈdiːvieɪt/", "meaning": "偏离；背离；越轨", "example": "Don't deviate from the plan."},
    {"word": "dilemma", "phonetic": "/dɪˈlemə/", "meaning": "困境；两难局面", "example": "She faced a moral dilemma."},
    {"word": "discipline", "phonetic": "/ˈdɪsɪplɪn/", "meaning": "纪律；自律；学科", "example": "Discipline is key to success."},
    {"word": "displace", "phonetic": "/dɪsˈpleɪs/", "meaning": "取代；移置；迫使离开", "example": "Many workers were displaced."},
    {"word": "dispose", "phonetic": "/dɪˈspəʊz/", "meaning": "处理；安排；使倾向", "example": "Dispose of waste properly."},
    {"word": "dispute", "phonetic": "/dɪˈspjuːt/", "meaning": "争议；争论；辩驳", "example": "The dispute was resolved peacefully."},
    {"word": "dominate", "phonetic": "/ˈdɒmɪneɪt/", "meaning": "支配；控制；俯视", "example": "Technology dominates modern life."},
    {"word": "drawback", "phonetic": "/ˈdrɔːbæk/", "meaning": "缺点；不利条件", "example": "Every plan has its drawbacks."},
    {"word": "dynamic", "phonetic": "/daɪˈnæmɪk/", "meaning": "动态的；有活力的；动力", "example": "The market is dynamic."},
    {"word": "efficient", "phonetic": "/ɪˈfɪʃnt/", "meaning": "高效的；有效率的", "example": "Find efficient ways to work."},
    {"word": "eliminate", "phonetic": "/ɪˈlɪmɪneɪt/", "meaning": "消除；淘汰；根除", "example": "Eliminate unnecessary steps."},
    {"word": "elite", "phonetic": "/eɪˈliːt/", "meaning": "精英；最优秀的；精英的", "example": "The elite control many resources."},
    {"word": "empirical", "phonetic": "/ɪmˈpɪrɪkl/", "meaning": "以经验为依据的；实证的", "example": "Empirical evidence supports the theory."},
    {"word": "enforce", "phonetic": "/ɪnˈfɔːs/", "meaning": "执行；强制；加强", "example": "Laws must be enforced consistently."},
    {"word": "enhance", "phonetic": "/ɪnˈhɑːns/", "meaning": "增强；提高；改善", "example": "Enhance your skills continuously."},
    {"word": "enormous", "phonetic": "/ɪˈnɔːməs/", "meaning": "巨大的；庞大的", "example": "The project required enormous effort."},
    {"word": "ensure", "phonetic": "/ɪnˈʃʊər/", "meaning": "确保；保证", "example": "Ensure accuracy in your work."},
    {"word": "enterprise", "phonetic": "/ˈentəpraɪz/", "meaning": "企业；事业；进取心", "example": "Start your own enterprise."},
    {"word": "equity", "phonetic": "/ˈekwɪti/", "meaning": "公平；平等；净资产", "example": "Equity in education is vital."},
    {"word": "equivalent", "phonetic": "/ɪˈkwɪvələnt/", "meaning": "等同的；相当的；等价物", "example": "This is equivalent to cheating."},
    {"word": "ethical", "phonetic": "/ˈeθɪkl/", "meaning": "道德的；伦理的", "example": "Make ethical business decisions."},
    {"word": "exceed", "phonetic": "/ɪkˈsiːd/", "meaning": "超过；超出；超越", "example": "Don't exceed the speed limit."},
    {"word": "exclusive", "phonetic": "/ɪkˈskluːsɪv/", "meaning": "独家的；排外的；高档的", "example": "An exclusive club."},
    {"word": "execute", "phonetic": "/ˈeksɪkjuːt/", "meaning": "执行；实施；处决", "example": "Execute the plan carefully."},
    {"word": "exempt", "phonetic": "/ɪɡˈzempt/", "meaning": "免除；豁免；被免除的", "example": "Some groups are exempt from tax."},
    {"word": "exhibit", "phonetic": "/ɪɡˈzɪbɪt/", "meaning": "展览；展示；表现", "example": "The museum exhibits ancient art."},
    {"word": "expertise", "phonetic": "/ˌekspɜːˈtiːz/", "meaning": "专业知识；专长", "example": "She has expertise in finance."},
    {"word": "extinction", "phonetic": "/ɪkˈstɪŋkʃn/", "meaning": "灭绝；消亡；熄灭", "example": "Many species face extinction."},
    {"word": "fabricate", "phonetic": "/ˈfæbrɪkeɪt/", "meaning": "捏造；制造；虚构", "example": "Don't fabricate data."},
    {"word": "feasible", "phonetic": "/ˈfiːzɪbl/", "meaning": "可行的；可能的", "example": "Is this plan feasible?"},
    {"word": "fluctuate", "phonetic": "/ˈflʌktʃueɪt/", "meaning": "波动；起伏；变动", "example": "Prices fluctuate daily."},
    {"word": "forecast", "phonetic": "/ˈfɔːkɑːst/", "meaning": "预测；预报；预计", "example": "The economic forecast is positive."},
    {"word": "foster", "phonetic": "/ˈfɒstər/", "meaning": "培养；促进；寄养", "example": "Foster creativity in students."},
    {"word": "fragile", "phonetic": "/ˈfrædʒaɪl/", "meaning": "脆弱的；易碎的", "example": "Handle fragile items with care."},
    {"word": "frustrate", "phonetic": "/frʌˈstreɪt/", "meaning": "使沮丧；阻挠；挫败", "example": "Repeated failure can frustrate learners."},
    {"word": "genuine", "phonetic": "/ˈdʒenjuɪn/", "meaning": "真正的；真诚的；真实的", "example": "Show genuine interest."},
    {"word": "governance", "phonetic": "/ˈɡʌvənəns/", "meaning": "治理；管理；统治", "example": "Good governance builds trust."},
    {"word": "habitat", "phonetic": "/ˈhæbɪtæt/", "meaning": "栖息地；产地；居住地", "example": "Protect the natural habitat."},
    {"word": "hence", "phonetic": "/hens/", "meaning": "因此；所以；从此", "example": "He was busy, hence the delay."},
    {"word": "hierarchy", "phonetic": "/ˈhaɪərɑːki/", "meaning": "等级制度；阶层；层次结构", "example": "Corporate hierarchy can limit innovation."},
    {"word": "highlight", "phonetic": "/ˈhaɪlaɪt/", "meaning": "强调；突出；亮点", "example": "Highlight the key points."},
    {"word": "homogeneous", "phonetic": "/ˌhɒməˈdʒiːniəs/", "meaning": "同质的；均匀的", "example": "A homogeneous society."},
    {"word": "ideal", "phonetic": "/aɪˈdɪəl/", "meaning": "理想的；完美的；理想", "example": "This is an ideal solution."},
    {"word": "ideology", "phonetic": "/ˌaɪdiˈɒlədʒi/", "meaning": "意识形态；思想体系", "example": "Political ideology shapes policy."},
    {"word": "illustrate", "phonetic": "/ˈɪləstreɪt/", "meaning": "说明；阐明；给…做插图", "example": "Use examples to illustrate your point."},
    {"word": "immense", "phonetic": "/ɪˈmens/", "meaning": "巨大的；广大的", "example": "The task required immense effort."},
    {"word": "implicit", "phonetic": "/ɪmˈplɪsɪt/", "meaning": "隐含的；含蓄的；无疑的", "example": "There was an implicit understanding."},
    {"word": "inclusive", "phonetic": "/ɪnˈkluːsɪv/", "meaning": "包容的；包括的；全面的", "example": "An inclusive learning environment."},
    {"word": "inevitable", "phonetic": "/ɪnˈevɪtəbl/", "meaning": "不可避免的；必然的", "example": "Change is inevitable."},
    {"word": "infer", "phonetic": "/ɪnˈfɜːr/", "meaning": "推断；推论；暗示", "example": "What can we infer from the data?"},
    {"word": "influence", "phonetic": "/ˈɪnfluəns/", "meaning": "影响；影响力；作用", "example": "Peer influence is strong."},
    {"word": "integrity", "phonetic": "/ɪnˈteɡrəti/", "meaning": "诚信；正直；完整性", "example": "Academic integrity must be upheld."},
    {"word": "intervene", "phonetic": "/ˌɪntəˈviːn/", "meaning": "干预；介入；调解", "example": "The government intervened in the crisis."},
    {"word": "intriguing", "phonetic": "/ɪnˈtriːɡɪŋ/", "meaning": "有趣的；迷人的；引人入胜的", "example": "An intriguing discovery was made."},
    {"word": "irrespective", "phonetic": "/ˌɪrɪˈspektɪv/", "meaning": "不考虑；不管；无论", "example": "Irrespective of age, all can learn."},
    {"word": "launch", "phonetic": "/lɔːntʃ/", "meaning": "启动；发射；发起", "example": "Launch a new product."},
    {"word": "legitimate", "phonetic": "/lɪˈdʒɪtɪmət/", "meaning": "合法的；正当的；合理的", "example": "Use legitimate means."},
    {"word": "liberal", "phonetic": "/ˈlɪbərəl/", "meaning": "自由的；开明的；宽容的", "example": "A liberal arts education."},
    {"word": "logical", "phonetic": "/ˈlɒdʒɪkl/", "meaning": "合乎逻辑的；合理的", "example": "His argument was logical."},
    {"word": "magnitude", "phonetic": "/ˈmæɡnɪtjuːd/", "meaning": "规模；大小；重要性", "example": "The magnitude of the problem is huge."},
    {"word": "mandatory", "phonetic": "/ˈmændətəri/", "meaning": "强制的；义务的；命令的", "example": "Attendance is mandatory."},
    {"word": "marginalize", "phonetic": "/ˈmɑːdʒɪnəlaɪz/", "meaning": "使边缘化；排斥", "example": "Don't marginalize minority groups."},
    {"word": "merit", "phonetic": "/ˈmerɪt/", "meaning": "优点；价值；功绩", "example": "Judge on merit, not appearance."},
    {"word": "methodology", "phonetic": "/ˌmeθəˈdɒlədʒi/", "meaning": "方法论；方法体系", "example": "Describe your research methodology."},
    {"word": "mitigate", "phonetic": "/ˈmɪtɪɡeɪt/", "meaning": "减轻；缓和；降低", "example": "Mitigate the risks carefully."},
    {"word": "mobility", "phonetic": "/məʊˈbɪləti/", "meaning": "流动性；移动性；机动性", "example": "Social mobility is declining."},
    {"word": "multitude", "phonetic": "/ˈmʌltɪtjuːd/", "meaning": "大量；众多；人群", "example": "A multitude of factors affect this."},
    {"word": "narrative", "phonetic": "/ˈnærətɪv/", "meaning": "叙述；故事；叙事的", "example": "The narrative was compelling."},
    {"word": "neutral", "phonetic": "/ˈnjuːtrəl/", "meaning": "中立的；中性的；不偏不倚", "example": "Remain neutral in disputes."},
    {"word": "nonetheless", "phonetic": "/ˌnʌnðəˈles/", "meaning": "尽管如此；然而；不过", "example": "It was hard; nonetheless, she succeeded."},
    {"word": "objective", "phonetic": "/əbˈdʒektɪv/", "meaning": "目标；客观的；客观", "example": "Be objective in your assessment."},
    {"word": "obstacle", "phonetic": "/ˈɒbstəkl/", "meaning": "障碍；阻碍；困难", "example": "Overcome obstacles with persistence."},
    {"word": "omit", "phonetic": "/əˈmɪt/", "meaning": "省略；遗漏；忽视", "example": "Don't omit important details."},
    {"word": "ongoing", "phonetic": "/ˈɒnɡəʊɪŋ/", "meaning": "持续的；进行中的", "example": "The investigation is ongoing."},
    {"word": "opinion", "phonetic": "/əˈpɪnjən/", "meaning": "意见；看法；评价", "example": "Share your opinion respectfully."},
    {"word": "optimistic", "phonetic": "/ˌɒptɪˈmɪstɪk/", "meaning": "乐观的；乐观主义的", "example": "Stay optimistic about the future."},
    {"word": "orientation", "phonetic": "/ˌɔːriənˈteɪʃn/", "meaning": "方向；取向；适应", "example": "Sexual orientation should be respected."},
    {"word": "paradigm", "phonetic": "/ˈpærədaɪm/", "meaning": "范例；典范；范式", "example": "A paradigm shift in thinking."},
    {"word": "parameter", "phonetic": "/pəˈræmɪtər/", "meaning": "参数；界限；决定因素", "example": "Set clear parameters for the project."},
    {"word": "passion", "phonetic": "/ˈpæʃn/", "meaning": "热情；激情；强烈爱好", "example": "Pursue your passion."},
    {"word": "passive", "phonetic": "/ˈpæsɪv/", "meaning": "被动的；消极的；顺从的", "example": "Avoid passive behavior."},
    {"word": "perception", "phonetic": "/pəˈsepʃn/", "meaning": "感知；认知；看法", "example": "Perception can differ from reality."},
    {"word": "persist", "phonetic": "/pəˈsɪst/", "meaning": "坚持；持续；固执", "example": "Persist despite difficulties."},
    {"word": "phase", "phonetic": "/feɪz/", "meaning": "阶段；时期；逐步进行", "example": "The project has three phases."},
    {"word": "philosophy", "phonetic": "/fɪˈlɒsəfi/", "meaning": "哲学；人生观；哲理", "example": "Study philosophy of science."},
    {"word": "pioneering", "phonetic": "/ˌpaɪəˈnɪərɪŋ/", "meaning": "开拓的；先驱的；先进的", "example": "Pioneering research in medicine."},
    {"word": "plausible", "phonetic": "/ˈplɔːzɪbl/", "meaning": "似乎合理的；可能的", "example": "A plausible explanation."},
    {"word": "predominance", "phonetic": "/prɪˈdɒmɪnəns/", "meaning": "优势；主导；支配", "example": "The predominance of English."},
    {"word": "prerequisite", "phonetic": "/ˌpriːˈrekwɪzɪt/", "meaning": "先决条件；前提；必要条件", "example": "Math is a prerequisite for this course."},
    {"word": "prevalent", "phonetic": "/ˈprevələnt/", "meaning": "普遍的；流行的；盛行的", "example": "Obesity is prevalent in many countries."},
    {"word": "proactive", "phonetic": "/ˌprəʊˈæktɪv/", "meaning": "主动的；积极进取的", "example": "Be proactive in solving problems."},
    {"word": "profound", "phonetic": "/prəˈfaʊnd/", "meaning": "深刻的；深远的；渊博的", "example": "A profound impact on society."},
    {"word": "prohibit", "phonetic": "/prəˈhɪbɪt/", "meaning": "禁止；阻止", "example": "Smoking is prohibited here."},
    {"word": "prominent", "phonetic": "/ˈprɒmɪnənt/", "meaning": "著名的；突出的；显眼的", "example": "A prominent scientist."},
    {"word": "prosperity", "phonetic": "/prɒˈsperəti/", "meaning": "繁荣；昌盛；成功", "example": "Economic prosperity benefits all."},
    {"word": "prototype", "phonetic": "/ˈprəʊtətaɪp/", "meaning": "原型；模型；典型", "example": "Build a prototype first."},
    {"word": "psychology", "phonetic": "/saɪˈkɒlədʒi/", "meaning": "心理学；心理；心理特点", "example": "Study psychology to understand behavior."},
    {"word": "qualitative", "phonetic": "/ˈkwɒlɪtətɪv/", "meaning": "定性的；质量的", "example": "Qualitative research explores experiences."},
    {"word": "quantitative", "phonetic": "/ˈkwɒntɪtətɪv/", "meaning": "定量的；数量的", "example": "Quantitative data shows numbers."},
    {"word": "radical", "phonetic": "/ˈrædɪkl/", "meaning": "根本的；激进的；彻底的", "example": "Radical change is needed."},
    {"word": "random", "phonetic": "/ˈrændəm/", "meaning": "随机的；任意的", "example": "A random sample was selected."},
    {"word": "realistic", "phonetic": "/ˌrɪəˈlɪstɪk/", "meaning": "现实的；实际的；逼真的", "example": "Set realistic expectations."},
    {"word": "recession", "phonetic": "/rɪˈseʃn/", "meaning": "经济衰退；后退；凹处", "example": "The country entered a recession."},
    {"word": "reinstate", "phonetic": "/ˌriːɪnˈsteɪt/", "meaning": "恢复；复原；使回复原位", "example": "The policy was reinstated."},
    {"word": "remedy", "phonetic": "/ˈremədi/", "meaning": "补救；治疗；解决办法", "example": "Find a remedy for the problem."},
    {"word": "repercussion", "phonetic": "/ˌriːpəˈkʌʃn/", "meaning": "反响；后果；影响", "example": "Consider the repercussions."},
    {"word": "reputation", "phonetic": "/ˌrepjuˈteɪʃn/", "meaning": "名誉；声誉；名声", "example": "Protect your professional reputation."},
    {"word": "resilience", "phonetic": "/rɪˈzɪliəns/", "meaning": "韧性；适应力；弹性", "example": "Build resilience through adversity."},
    {"word": "retain", "phonetic": "/rɪˈteɪn/", "meaning": "保留；保持；记住", "example": "Retain key employees."},
    {"word": "rhetoric", "phonetic": "/ˈretərɪk/", "meaning": "修辞；言辞；花言巧语", "example": "Political rhetoric can mislead."},
    {"word": "rigorous", "phonetic": "/ˈrɪɡərəs/", "meaning": "严格的；严密的；彻底的", "example": "Rigorous testing is required."},
    {"word": "robust", "phonetic": "/rəʊˈbʌst/", "meaning": "强健的；稳健的；坚固的", "example": "A robust system can handle errors."},
    {"word": "scope", "phonetic": "/skəʊp/", "meaning": "范围；机会；视野", "example": "Broaden the scope of the research."},
    {"word": "segregate", "phonetic": "/ˈseɡrɪɡeɪt/", "meaning": "隔离；分开；歧视", "example": "Don't segregate people."},
    {"word": "sequence", "phonetic": "/ˈsiːkwəns/", "meaning": "顺序；序列；系列", "example": "Follow the correct sequence."},
    {"word": "socioeconomic", "phonetic": "/ˌsəʊsiəʊˌiːkəˈnɒmɪk/", "meaning": "社会经济的", "example": "Socioeconomic factors affect health."},
    {"word": "sophisticated", "phonetic": "/səˈfɪstɪkeɪtɪd/", "meaning": "复杂的；精密的；老练的", "example": "A sophisticated approach."},
    {"word": "speculate", "phonetic": "/ˈspekjəleɪt/", "meaning": "推测；投机；思索", "example": "Don't speculate without evidence."},
    {"word": "stimulus", "phonetic": "/ˈstɪmjələs/", "meaning": "刺激；激励；刺激物", "example": "A stimulus package was introduced."},
    {"word": "subjective", "phonetic": "/səbˈdʒektɪv/", "meaning": "主观的；个人的", "example": "Art appreciation is subjective."},
    {"word": "subsequent", "phonetic": "/ˈsʌbsɪkwənt/", "meaning": "随后的；后来的；继……之后", "example": "Subsequent research confirmed this."},
    {"word": "substantial", "phonetic": "/səbˈstænʃl/", "meaning": "大量的；实质性的；重要的", "example": "Substantial evidence is needed."},
    {"word": "subtle", "phonetic": "/ˈsʌtl/", "meaning": "微妙的；细微的；精巧的", "example": "A subtle difference exists."},
    {"word": "supplement", "phonetic": "/ˈsʌplɪment/", "meaning": "补充；增补；补充物", "example": "Supplement your income with freelancing."},
    {"word": "suppress", "phonetic": "/səˈpres/", "meaning": "压制；镇压；抑制", "example": "Suppress negative emotions healthily."},
    {"word": "surveillance", "phonetic": "/sɜːˈveɪləns/", "meaning": "监视；监察；监控", "example": "Government surveillance is controversial."},
    {"word": "sustainable", "phonetic": "/səˈsteɪnəbl/", "meaning": "可持续的；可维持的", "example": "Sustainable development is essential."},
    {"word": "systematic", "phonetic": "/ˌsɪstəˈmætɪk/", "meaning": "系统的；有条理的", "example": "A systematic approach works best."},
    {"word": "terminate", "phonetic": "/ˈtɜːmɪneɪt/", "meaning": "终止；结束；解雇", "example": "The contract was terminated early."},
    {"word": "theoretical", "phonetic": "/ˌθɪəˈretɪkl/", "meaning": "理论的；假设的", "example": "A theoretical framework is needed."},
    {"word": "thorough", "phonetic": "/ˈθʌrə/", "meaning": "彻底的；详尽的；认真的", "example": "Do a thorough analysis."},
    {"word": "tolerance", "phonetic": "/ˈtɒlərəns/", "meaning": "容忍；宽容；耐受性", "example": "Tolerance of different views is vital."},
    {"word": "transparent", "phonetic": "/trænsˈpærənt/", "meaning": "透明的；显而易见的；坦诚的", "example": "Government should be transparent."},
    {"word": "ultimate", "phonetic": "/ˈʌltɪmət/", "meaning": "最终的；终极的；根本的", "example": "The ultimate goal is happiness."},
    {"word": "underlie", "phonetic": "/ˌʌndəˈlaɪ/", "meaning": "成为…的基础；在…之下", "example": "Several factors underlie this trend."},
    {"word": "unpredictable", "phonetic": "/ˌʌnprɪˈdɪktəbl/", "meaning": "不可预测的；变化无常的", "example": "Weather is unpredictable."},
    {"word": "unprecedented", "phonetic": "/ʌnˈpresɪdentɪd/", "meaning": "史无前例的；空前的", "example": "Unprecedented growth was recorded."},
    {"word": "urgent", "phonetic": "/ˈɜːdʒənt/", "meaning": "紧急的；迫切的；急迫的", "example": "This is an urgent matter."},
    {"word": "venture", "phonetic": "/ˈventʃər/", "meaning": "冒险；企业；大胆探索", "example": "Launch a new business venture."},
    {"word": "versatile", "phonetic": "/ˈvɜːsətaɪl/", "meaning": "多才多艺的；多功能的", "example": "A versatile employee is valuable."},
    {"word": "virtually", "phonetic": "/ˈvɜːtʃuəli/", "meaning": "实际上；几乎；虚拟地", "example": "Virtually all students passed."},
    {"word": "voluntary", "phonetic": "/ˈvɒləntri/", "meaning": "自愿的；志愿的；无偿的", "example": "Participation is voluntary."},
    {"word": "vulnerability", "phonetic": "/ˌvʌlnərəˈbɪləti/", "meaning": "脆弱性；易受伤害", "example": "Acknowledge your vulnerability."},
    {"word": "welfare", "phonetic": "/ˈwelfeər/", "meaning": "福利；幸福；福祉", "example": "Child welfare is a priority."},
    {"word": "withstand", "phonetic": "/wɪðˈstænd/", "meaning": "承受；抵抗；经受住", "example": "The bridge can withstand earthquakes."},
]
